# deploy to wordpress and also create a release on github
name: Deploy to Github (not to WordPress)
on:
  push:
    tags:
    - 'v*-alpha*'
    - 'v*-beta*'
    - 'v*-rc*'
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: |
        composer install --no-dev --optimize-autoloader
    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
        dry-run: true
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
    - name: Create GH Pre-release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.deploy.outputs.zip-path }}
        artifactContentType: application/zip
        prerelease: true